### ISSUE TITLE
Add bez pens?

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/psautohint#8]
Would it be feasible/useful to have pens that convert to and from [bez format](https://github.com/khaledhosny/psautohint/blob/master/doc/bezfileformat.txt)?

**Comment by khaledhosny** [comment]
I started working on this in the `pens` branch, but its seems that the bez data my pen is generating is causing the autohinter to generate different hints. I notice that the written back glyph outlines have different contour order which might be the cause behind the differences I’m seeing, though I don’t know what would be the cause for this.

**Comment by behdad** [comment]
What is the bez format used for anyway?  Why not just the chartring operator names?

**Comment by khaledhosny** [comment]
I don’t know for sure, and I considered renaming the bez operators to be just a text representation of the charstrings, but decided to postpone this for now to avoid touch the C code more. I don’t think it would make much of a difference though since it seems to expect small subset set of the operators; `rmoveto`, `rlineto` and `rrcurveto` (at least this what the old python code is doing), so we will need a code to simplify and serialize the charstring anyway.

**Comment by khaledhosny** [comment]
`wip/pens` has something that works for converting CFF CharStrings to Bez format. However, I now think my original idea is not going to work since the pen protocol does not support hinting at all so I can’t only use pens to convert Bez ↔ UFO/CFF CharStrings without complicating things, while we have already working code (albeit being a bit low level to my taste).

I guess I better close this and check later if things changed.
